import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const posts = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/posts' }),
  schema: z.object({
    title: z.string(),
    metaDescription: z.string().default(''),
    targetKeyword: z.string().default(''),
    pillar: z.enum(['business', 'culture', 'finance', 'travel', 'lifestyle', 'tech', 'food', 'entertainment']),
    contentType: z.enum([
      'article',
      'essay',
      'guide',
      'experiment',
      'tool-page',
      'resource-page',
      'playbook',
      'affiliate-stack',
      'restaurant-guide',
      'hotel-review',
      'travel-guide',
      'style-guide',
      'recipe',
      'the-edit',
      'destination-hub',
    ]).default('article'),
    date: z.string(),
    updatedDate: z.string().optional(),
    image: z.string().default(''),
    imageAlt: z.string().default(''),
    excerpt: z.string().default(''),
    author: z.string().default('Evan Ratner'),
    draft: z.boolean().default(false),
    featured: z.boolean().default(false),
    featuredOrder: z.number().optional(),
    destinations: z.array(z.string()).default([]),
    tags: z.array(z.string()).default([]),
    faq: z.array(z.object({
      question: z.string(),
      answer: z.string(),
    })).default([]),
    products: z.array(z.object({
      name: z.string(),
      brand: z.string().optional(),
      price: z.string().optional(),
      url: z.string().optional(),
      image: z.string().optional(),
    })).default([]),
    bookingLinks: z.array(z.object({
      name: z.string(),
      platform: z.string().optional(),
      url: z.string().optional(),
    })).default([]),
    reservationLinks: z.array(z.object({
      name: z.string(),
      platform: z.string().optional(),
      url: z.string().optional(),
    })).default([]),
    restaurants: z.array(z.object({
      name: z.string(),
      description: z.string().optional(),
      whyItStandsOut: z.string().optional(),
      address: z.string().optional(),
      reservationUrl: z.string().optional(),
      cuisine: z.string().optional(),
      priceRange: z.string().optional(),
      neighborhood: z.string().optional(),
    })).default([]),
    quickPicks: z.array(z.string()).default([]),
    hotelDetails: z.object({
      propertyName: z.string().optional(),
      propertyType: z.string().optional(),
      priceTier: z.string().optional(),
      goodFor: z.array(z.string()).default([]),
      standoutFeatures: z.array(z.string()).default([]),
      alternatives: z.array(z.string()).default([]),
    }).optional(),
    prepTime: z.string().optional(),
    cookTime: z.string().optional(),
    totalTime: z.string().optional(),
    servings: z.string().optional(),
    ingredients: z.array(z.string()).default([]),
    instructions: z.array(z.string()).default([]),
    nutrition: z.object({
      calories: z.string().optional(),
      servingSize: z.string().optional(),
    }).optional(),
    affiliateDisclosure: z.boolean().default(false),
    relatedPosts: z.array(z.string()).default([]),
    voiceScore: z.number().optional(),
    seoScore: z.number().optional(),
    pinsGenerated: z.number().default(0),
    newsletterIncluded: z.boolean().default(false),
    toc: z.boolean().default(false),
    sourceUrl: z.string().optional(),
    cornerstone: z.boolean().default(false),
    subcategory: z.string().optional(),
    ogTitle: z.string().optional(),
    ogDescription: z.string().optional(),
    imageCaption: z.string().optional(),
    imageCredit: z.string().optional(),
    canonicalOverride: z.string().optional(),
    season: z.string().optional(),
    newsletterCTAVariant: z.enum(['inline', 'bold', 'destination', 'shopping']).optional(),
    // Archive metadata fields (for reactivation engine)
    source: z.enum(['ratlinks', 'substack', 'wordpress', 'original', 'other']).default('original'),
    originalDate: z.string().optional(),
    evergreenScore: z.number().default(0),
    distributionScore: z.number().default(0),
    monetizationScore: z.number().default(0),
    derivativeScore: z.number().default(0),
    urgencyScore: z.number().default(0),
    opportunitySummary: z.string().default(''),
    refreshPriority: z.enum(['high', 'medium', 'low', 'none']).default('none'),
    evergreenClass: z.enum([
      'evergreen-flagship',
      'evergreen-needs-refresh',
      'archive-only',
      'derivative-candidate',
      'seo-derivative-candidate',
      'affiliate-candidate',
      'newsletter-reshare',
      'social-reshare',
      'playbook-candidate',
      'low-priority',
    ]).default('archive-only'),
    classificationBuckets: z.array(z.string()).default([]),
    status: z.enum(['imported', 'classified', 'refreshed', 'redistributed', 'monetized']).default('imported'),
    refreshedDate: z.string().optional(),
    monetizationPotential: z.enum(['high', 'medium', 'low', 'none']).default('none'),
    derivativePotential: z.enum(['high', 'medium', 'low', 'none']).default('none'),
    suggestedDerivatives: z.array(z.string()).default([]),
    suggestedAffiliates: z.array(z.string()).default([]),
    suggestedInternalLinks: z.array(z.string()).default([]),
    bundleId: z.string().optional(),
    reactivated: z.boolean().default(false),
  }),
});

export const collections = { posts };
